version: '2'

services:
  # Zookeeper Container
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.8
    ports: 
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # Kafka Container
  kafka:
    container_name: kafka
    image: bitnami/kafka:3.4
    ports: 
      - 9092:9092
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      - KAFKA_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  # POSTGRESS CONTAINER
  postgres:
    container_name: postgres
    image: postgres
    ports: 
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=customer
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  # MARKETER CONTAINER
  marketer:
    container_name: marketer
    build: ./marketer
    ports: 
      - 8081:8081
    volumes:
      - ./marketer:/app
    environment:
      - PORT=8081
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - KAFKA_TOPIC=offer
    depends_on:
      - kafka
    restart: always

  # CUSTOMER CONTAINER
  customer:
    container_name: customer
    build: ./customer
    ports: 
      - 8082:8082
    volumes:
      - ./customer:/app
    environment:
      - PORT=8082
      - PG_DB=customer
      - PG_USER=root
      - PG_PASSWORD=root
      - PG_HOST=postgres
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - KAFKA_TOPIC=offer
    depends_on:
      - postgres
      - kafka
      - marketer
    restart: always